### ISSUE TITLE
Replace Trireme-CSR identity generation to use OpenSSL

### ISSUE THREAD

**Issue by mheese** [aporeto-inc/trireme-kubernetes#133]
Currently the `gen_pki_ca.sh` script in the deployments folder is using `tg` for generating the p12 file. Even though I like `tg` we should switch to just use openssl as it becomes one dependency less in the getting started section.

**Comment by bvandewalle** [comment]
Yes fully agree. This is for the quick deploy guide, we should provide the plain openssl commands to deploy a self-signed environment.

This cannot be used for deployment of course.

**Comment by bvandewalle** [comment]
A quick idea:
Why not using an init container that will generate the PKI CA for Trireme-CSR, to be used with the quick-deploy guide ?

This is just a way to allow the user to not use the PKI Generation script when using the quick deploy guide

**Comment by mheese** [comment]
Yeah, let's switch to that. I'll open up a new issue for that.

**Comment by mheese** [comment]
Closing this in favour of #139
