### ISSUE TITLE
Server could not find CRD

### ISSUE THREAD

**Issue by andrewrynhard** [aporeto-inc/trireme-kubernetes#148]
Following the quick start, I get:

```
kubectl logs trireme-csr-controller-5zssq -n kube-system
INFO	start watching Certificates objects
INFO	Everything started. Waiting for Stop signal
ERROR: logging before flag.Parse: E0222 22:43:19.574805       1 reflector.go:205] github.com/aporeto-inc/trireme-csr/controller/controller.go:65: Failed to list *v1alpha2.Certificate: the server could not find the requested resource (get certificates.certmanager.k8s.io)
...
```

Kubernetes v1.9.3

**Comment by andrewrynhard** [comment]
https://github.com/aporeto-inc/trireme-csr/issues/27

**Comment by mheese** [comment]
@andrewrynhard , your problem is most likely this file `https://github.com/aporeto-inc/trireme-kubernetes/blob/master/deployment/trireme/certificate-crd.yaml` ... please change the version in the CRD from `v1alpha1` to `v1alpha2`. We recently bumped up the API version, and I must have forgotten about this file

**Comment by mheese** [comment]
it's actually going to be fixed once https://github.com/aporeto-inc/trireme-kubernetes/pull/147 gets merged.

**Comment by andrewrynhard** [comment]
@mheese that got the controller to run, thanks! Now I am seeing this:

```
FATAL	error loading Certificates for PKI Trireme	{"error": "Error Sending and waiting couldn't create CSR Kube object: Certificate.certmanager.k8s.io \"ip-10-35-122-114\" is invalid: metadata.namespace: Required value"}
```

**Comment by andrewrynhard** [comment]
Think I might need:

```
scope: Cluster
``` 
in the CRD.

**Comment by mheese** [comment]
@andrewrynhard yes, exactly ... as in the file in the PR. Sorry about that.
