### ISSUE TITLE
Docs: Trireme depends on `raw` iptables module

### ISSUE THREAD

**Issue by thockin** [aporeto-inc/trireme-kubernetes#25]
Believe it or not, some distros do not ship with it.  Sigh.  Better error handling in this case would be nice, but at least docs...

**Comment by bvandewalle** [comment]
@thockin  We are working to add test coverage both for Trireme (Where that issue actually is) and Trireme-Kubernetes.
We indeed need to catch when `raw` is not available. I don't think we can make it work without `raw`. 
I'm updating the doc to list a couple requirements.
What distro are you using btw ?

**Comment by thockin** [comment]
Google's newer image.  The issue will be fixed, but it was not obvious why
it was broken :)

**Comment by bvandewalle** [comment]
@thockin : 
We managed to make Trireme work without the need of the raw table at all.

It is still being tested at this point, but if you use the GKE branch on this repo, it should work out of the box on GKE (we tested this on our end). I imagine that your distro must be somewhat similar:
https://github.com/aporeto-inc/trireme-kubernetes/tree/GKE/deployment

Let us know!

**Comment by davidebelloni** [comment]
Hi,
I'm trying to activate Trireme on GKE without success. When I apply the policy I've the following error:

> time="2017-02-27T16:20:58Z" level=info msg="PID of container" package=enforcerproxy pid=20802 
> time="2017-02-27T16:20:58Z" level=info msg="Called enforce and launched process" Lauch Process=<nil> contexID=4774aa96d4ce package=enforcerproxy 
> time="2017-02-27T16:20:58Z" level=debug msg="Enforce IP" contextID=4774aa96d4ce package=enforcer 
> time="2017-02-27T16:20:58Z" level=info msg="ENFORCE STATUS" error=<nil> method=Enforce package="remote_enforcer" 
> time="2017-02-27T16:20:58Z" level=info msg="Called Supervise Start in remote_enforcer" method=Supervise package="remote_enforcer" 
> time="2017-02-27T16:20:58Z" level=error msg="Received a container event in Remote Enforcer " Msg="Unexpected call to CollectContainer Event" package=remoteEnforcer 
> 

What can I verify?
I'm using the "GKE" branch info (like _aporeto/trireme-gke_ image usage).

Instead if I use the trireme-kubernetes image the packet from internet is dropped by the following chain:

```
Chain TRIREME-Net-d1f2a9d2b745-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 NFQUEUE    tcp  --  *      *       10.0.0.0/8           0.0.0.0/0            connbytes 0:3 connbytes mode packets connbytes direction original NFQUEUE balance 4:7
    5   240 DROP       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW
```

Is it possible with Trireme to apply an Internet ingress allow?

**Comment by bvandewalle** [comment]
@thockin : Can you try again on your image? We moved Trireme to a "remote-enforcer" model. This means that we directly provision IPTables on the network namespace of the Pods. We don't need the RAW table anymore

**Comment by bvandewalle** [comment]
@davidebelloni : The new image we released should make this work as we discussed :)
