### ISSUE TITLE
Docker client version newer then server

### ISSUE THREAD

**Issue by george-angel** [aporeto-inc/trireme-kubernetes#29]
Getting following errors trying to run on `CoreOS stable (1122.3.0)`:

```
I1113 12:12:36.368400       7 docker.go:241] Received docker event error  Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
I1113 12:12:36.379466       7 docker.go:184] Error Syncing existingContainers: %s Error Getting ContainerList: Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)
```

If I understand correctly this should be higher level then INFO? It means that currently running containers will not have the policies applied to them?

**Comment by bvandewalle** [comment]
Indeed, this means that we don't get any information from the Docker event API, which makes Trireme unable to apply policies on container.
This issue actually belongs in the Trireme repo ( https://github.com/aporeto-inc/trireme ). 
We are looking into it, Thanks for reporting.

**Comment by george-angel** [comment]
I can see you already support tcp socket connections: https://github.com/aporeto-inc/trireme/blob/master/monitor/docker.go#L73-L74 which would serve better in this case as its more forgiving to version changes between the client and the server.
