### ISSUE TITLE
create daemonSetPSK.yaml failed

### ISSUE THREAD

**Issue by hoanhdo** [aporeto-inc/trireme-kubernetes#48]
Hi.
I run kubernetes 1.5 on centos 7

> CentOS Linux release 7.2.1511 (Core) 

> 
> kubernetes-node-1.5.2-0.2.gitc55cf2b.el7.x86_64
> kubernetes-client-1.5.2-0.2.gitc55cf2b.el7.x86_64
> kubernetes-1.5.2-0.2.gitc55cf2b.el7.x86_64
> kubernetes-master-1.5.2-0.2.gitc55cf2b.el7.x86_64
> 

I added --allow_privileged=true to kubelet and kube-apiserver config

> KUBE_API_ARGS="--allow_privileged=true"

> KUBELET_ARGS="--cluster-dns=10.254.3.100 --cluster-domain=cluster.local --allow_privileged=true"

after run kubectl create -f daemonSetPSK.yaml, this is logs pods

> I0404 08:51:37.970473   23665 main.go:42] Config used: &{KubeEnv:true AuthType:PSK KubeNodeName:10.3.105.10 NodeAnnotationKey: PKIDirectory: KubeConfigLocation: TriremePSK:b2M+RGBRNKu7FjiUovYb0A== TriremeNets:[10.0.0.0/8] ExistingContainerSync:true Enforcer:false RemoteEnforcer:true LogLevel:debug} 
> W0404 08:51:37.971420   23665 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0404 08:51:37.971455   23665 client_config.go:522] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
> Error initializing KubernetesPolicy, exiting: Couldn't create KubernetesClient: Couldn't initialize Kubernetes Client: Error Building InCluster config: invalid configuration: default cluster has no server defined  
> 

Thanks.

**Comment by hoanhdo** [comment]
How i can set Env KubeConfigLocation.
I tried KUBECONFIGLOCATION, KUBE_CONFIG_LOCATION.
thanks.

**Comment by bvandewalle** [comment]
Hi @hoanhdo . This is weird, because the "in-cluster" authentication based on the mounted token should just work (That's why by default it's so easy).
In your case, it seems that the token was not found:

```
W0404 08:51:37.971455 23665 client_config.go:522] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

Actually the way the code for the configuration is written today it will not take the kubeconfig flag into account unless you are not into a Kubernetes environment. 
It is easy to add a support for specifying the KubeConfig location even if you are into a Kubernetes environment, but I would instead suggest to debug why the in cluster token is not available.

If you do a `kubectl describe pod`, do you see the token mounted on your pod  ?

**Comment by hoanhdo** [comment]
Hi @bvandewalle 
yes. Token not avaiable. I create serviceaccount but token not auto generates.
This is my describe pod.
 

> ---------     --------        -----   ----                    -------------                   --------        ------          -------
>   3m            3m              1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal          Created         Created container with docker id e765d1f121fa; Security:[seccomp=unconfined]
>   3m            3m              1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal          Started         Started container with docker id e765d1f121fa
>   3m            3m              1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal          Created         Created container with docker id 1fe57755b67a; Security:[seccomp=unconfined]
>   3m            3m              1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal          Started         Started container with docker id 1fe57755b67a
>   3m            3m              2       {kubelet 10.3.105.10}                                   Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "trireme" with CrashLoopBackOff: "Back-off 10s restarting failed container=trireme pod=trireme-c07t9_default(96281db4-1c04-11e7-9028-fa163e18ff5e)"
> 
>   3m    3m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Created         Created container with docker id e086e424dd2b; Security:[seccomp=unconfined]
>   3m    3m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Started         Started container with docker id e086e424dd2b
>   3m    3m      2       {kubelet 10.3.105.10}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "trireme" with CrashLoopBackOff: "Back-off 20s restarting failed container=trireme pod=trireme-c07t9_default(96281db4-1c04-11e7-9028-fa163e18ff5e)"
> 
>   2m    2m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Created         Created container with docker id b4bcd4fb819c; Security:[seccomp=unconfined]
>   2m    2m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Started         Started container with docker id b4bcd4fb819c
>   2m    2m      4       {kubelet 10.3.105.10}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "trireme" with CrashLoopBackOff: "Back-off 40s restarting failed container=trireme pod=trireme-c07t9_default(96281db4-1c04-11e7-9028-fa163e18ff5e)"
> 
>   2m    2m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Started         Started container with docker id f127f84480ab
>   2m    2m      1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Created         Created container with docker id f127f84480ab; Security:[seccomp=unconfined]
>   2m    1m      7       {kubelet 10.3.105.10}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "trireme" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=trireme pod=trireme-c07t9_default(96281db4-1c04-11e7-9028-fa163e18ff5e)"
> 
>   3m    45s     6       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Pulling         pulling image "aporeto/trireme-kubernetes"
>   3m    42s     6       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Pulled          Successfully pulled image "aporeto/trireme-kubernetes"
>   42s   42s     1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Created         Created container with docker id e2bca16ef7fc; Security:[seccomp=unconfined]
>   42s   42s     1       {kubelet 10.3.105.10}   spec.containers{trireme}        Normal  Started         Started container with docker id e2bca16ef7fc
>   3m    0s      20      {kubelet 10.3.105.10}   spec.containers{trireme}        Warning BackOff         Back-off restarting failed docker container
>   40s   0s      5       {kubelet 10.3.105.10}                                   Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "trireme" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=trireme pod=trireme-c07t9_default(96281db4-1c04-11e7-9028-fa163e18ff5e)"
> 
Thanks.

**Comment by hoanhdo** [comment]
i resolved by configure tls for apiserver and control-manager.
Thanks.
