### ISSUE TITLE
Loop recreating pod trireme

### ISSUE THREAD

**Issue by hoanhdo** [aporeto-inc/trireme-kubernetes#49]
Hi.
I run trireme-kubernetes daemonset. Pod is running but loop restart.
It make other pods restart.
My logs in attach file.
[log.txt](https://github.com/aporeto-inc/trireme-kubernetes/files/913448/log.txt)

Thanks

**Comment by bvandewalle** [comment]
Hi. This should be fixed since a couple versions now. Thanks for reporting.
