### ISSUE TITLE
Prerequisites details

### ISSUE THREAD

**Issue by hoanhdo** [aporeto-inc/trireme-kubernetes#50]
Hi all.
This is prerequisites of trieme.
> 
> 
>     Trireme requires IPTables with access to the Mangle module.
>     Trireme requires access to the Docker event API socket (/var/run/docker.sock by default)
>     Trireme requires privileged access
>     Trireme requires to run on the Host PID Namespace.
>     When deploying with the DaemonSet model, Trireme requires access to the in-cluster service API/Token. The Namespaces/Pods/NetworkPolicies must be available as read-only

If i install on centos 7.
This is my task/
- install iptables with module mangle module
- mount dockersock in trieme daemonsets
- assign privileged=true in kube-apiserver and kubelet
- I don't know
- config tls for kubernetes apiserver to create secret token for namespaces.

Onething  what is TRIREME_NETS in daemonsets yaml.
Is this network cidr of kubernetes.

Thanks.

**Comment by mingfang** [comment]
I also want to know what is TRIREME_NETS?

**Comment by bvandewalle** [comment]
Hi @hoanhdo @mingfang  : Thanks for reporting.
Initially, Trireme-Nets were the CIDR of all Networks on which Trireme//Kubernetes would run. 

In the latest version, we remove the need for specifying that parameter. Essentially it makes it super easy to deploy now. Can you give it another try ? (`README` will be updated soon
