### ISSUE TITLE
daemonSetPKI is starting in PSK mode

### ISSUE THREAD

**Issue by nicholasporcaro** [aporeto-inc/trireme-kubernetes#55]
As the title says. I have a fresh kubeadm-based install of 1.6.3 on baremetal, and when using `daemonSetPKI.yaml`, I get perpetual `CrashLoopBackOff`. When looking at the logs, I see this at the top:

`I0519 22:50:20.261002   24703 main.go:63] Starting Trireme PSK`

Then the pods never start because of 403s:

`I0519 22:50:20.348706   24703 round_trippers.go:417] GET https://10.96.0.1:443/api/v1/namespaces/default/pods/trireme-df3ck 403 Forbidden in 38 milliseconds`

I will be plugging away at why it's starting in PSK mode, but any help would be appreciated

**Comment by bvandewalle** [comment]
Hi @nicholasporcaro : Thanks for reporting. This is now fixed since a couple versions.
