### ISSUE TITLE
Example needs changes to work

### ISSUE THREAD

**Issue by leopoldodonnell** [aporeto-inc/trireme-kubernetes#59]
I attempted to run the basic demo as described in the demo, but it requires a bit of work to get
working (As of June 2017). Neither the default nginx nor redis come with wget or curl installed. This should be noted, or other images suggested.

Perhaps add
```
RUN apt-get update && apt-get install -y wget
```
to the instructions

It may also be more useful to swap redis in the frontend with nginx in the backend and vice-versa

**Comment by derezed88** [comment]
redis:3.2.6 has wget, I'll work on getting the pod yaml updated.  Thanks!

**Comment by bvandewalle** [comment]
Thanks for reporting.
We are working on an easy to use example! Will update with the example shortly.

**Comment by bvandewalle** [comment]
Everything was refactored and the example is now apobeer. Please retry. Thanks!
